name: TestNDeploy

on: [push, pull_request]

jobs:
  test_load_pr_info:
    name: Caching
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]

    services:
      motoserver:
        image: ghcr.io/getmoto/motoserver:latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: |
          python -m pip install --upgrade pip
      - name: Install project dependencies
        if: ${{ steps.pip-cache.outputs.cache-hit != 'true' }}
        run: |
          pip install -r backend/requirements.txt
      - name: Prepare TF to run against MotoServer
        run: |
          rm provider.tf
          mv provider.mock provider.tf
      - name: Run TF
        run: |
          terraform init
          terraform apply -target=aws_dynamodb_table.pull-requests -auto-approve
      - name: Execute tests
        run: |
          echo "TODO"
